# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Samples Integration Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  integrate-test:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.14

      - name: "Checkout Samples Repo"
        uses: actions/checkout@v3
        with:
          path: incubator-seata-go-samples

      - name: "Checkout Main Seata-Go Repo"
        uses: actions/checkout@v3
        with:
          repository: apache/incubator-seata-go
          ref: master
          path: incubator-seata-go

      - name: "Link Repositories via Go Workspace"
        run: |
          go work init
          go work use ./incubator-seata-go
          go work use ./incubator-seata-go-samples
        working-directory: ${{ github.workspace }}

      - name: "Cache Dependencies"
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Execute Integration Tests"
        run: |
          sed -i 's/docker-compose /docker compose /g' start_integrate_test.sh

          chmod +x start_integrate_test.sh
          chmod +x integrate_test.sh
          chmod +x dockercompose/docker-health-check.sh
          ./start_integrate_test.sh
        working-directory: ${{ github.workspace }}/incubator-seata-go-samples